version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: dynabase-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: dynabase-keycloak
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
